---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Deactivate the default nginx from sites-available
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Copy demo.dglte.net
  template:
    src: demo.dglte.net
    dest: /etc/nginx/sites-available/

- name: Activate the demo.dglte.net site
  file: 
    src: /etc/nginx/sites-available/demo.dglte.net
    dest: /etc/nginx/sites-enabled/demo.dglte.net
    state: link

- name: Restart nginx.service
  systemd:
    state: restarted
    name: nginx