- name: Clone django project repository
  git:
    repo: "https://github.com/ciur/django-lessons-proj.git"
    dest: "{{projdir}}"
    version: master
  become_user: john

- name: Install production.py
  template:
    src: production.py
    dest: "{{projdir}}/config/settings/production.py"
  become_user: john

- name: Create virtualenv and run pip install -r requirement.freeze
  pip:
    virtualenv: "{{projdir}}/venv"
    requirements: "{{projdir}}/requirements.freeze"
    virtualenv_command: "/usr/bin/python3 -m venv"
  become_user: john

- name: Run migrate
  django_manage:
    command: collectstatic
    app_path: "{{projdir}}"
    settings: "config.settings.production"
    virtualenv: "{{projdir}}/venv"
  become_user: john 
  environment:
    SECRET_KEY: "{{secret_key}}"
    DB_NAME: "{{db_name}}"
    DB_USER: "{{db_user}}"
    DB_PASS: "{{db_pass}}"
    AWS_STORAGE_BUCKET_NAME: "{{aws_storage_bucket_name}}"
    AWS_S3_REGION_NAME: "{{aws_s3_region_name}}"
    AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
    AWS_S3_CUSTOM_DOMAIN: "{{aws_s3_custom_domain}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"

- name: Run collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{projdir}}"
    settings: "config.settings.production"
    virtualenv: "{{projdir}}/venv"
  become_user: john
  environment:
    SECRET_KEY: "{{secret_key}}"
    DB_NAME: "{{db_name}}"
    DB_USER: "{{db_user}}"
    DB_PASS: "{{db_pass}}"
    AWS_STORAGE_BUCKET_NAME: "{{aws_storage_bucket_name}}"
    AWS_S3_REGION_NAME: "{{aws_s3_region_name}}"
    AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
    AWS_S3_CUSTOM_DOMAIN: "{{aws_s3_custom_domain}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"

